"""add to log table filed username

Revision ID: 04f1b34897c4
Revises: 698390eb4c9a
Create Date: 2019-11-11 23:33:53.494540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f1b34897c4'
down_revision = '698390eb4c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_client', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_client', 'username')
    # ### end Alembic commands ###
