"""Start

Revision ID: 4606822aa4f4
Revises: 
Create Date: 2019-07-23 22:17:29.445656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4606822aa4f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.create_table('eqptmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('svlan', sa.Integer(), nullable=True),
    sa.Column('netlan', sa.Integer(), nullable=True),
    sa.Column('netmask', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.Integer(), nullable=True),
    sa.Column('dns', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netlan')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('radius_grup_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eqpt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(length=50), nullable=True),
    sa.Column('mac', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['eqptmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_street_name'), 'street', ['name'], unique=False)
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_name'), 'building', ['name'], unique=False)
    op.create_table('eqptport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eqpt_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('cvlan', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('radius_user', sa.String(length=20), nullable=True),
    sa.Column('radius_pass', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['eqpt_id'], ['eqpt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('eqptport_id', sa.Integer(), nullable=True),
    sa.Column('fio', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eqptport_id'], ['eqptport.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networkhost',
    sa.Column('host', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('eqptport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eqptport_id'], ['eqptport.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('host')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('networkhost')
    op.drop_table('client')
    op.drop_table('eqptport')
    op.drop_index(op.f('ix_building_name'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_street_name'), table_name='street')
    op.drop_table('street')
    op.drop_table('eqpt')
    op.drop_table('service')
    op.drop_table('network')
    op.drop_table('eqptmodel')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
