"""client add note field

Revision ID: 5f4853bfd22b
Revises: 76f31dce8c82
Create Date: 2019-11-02 22:18:23.065750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4853bfd22b'
down_revision = '76f31dce8c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('note', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'note')
    # ### end Alembic commands ###
