"""add radius

Revision ID: 6f51515ef13a
Revises: 
Create Date: 2019-11-24 15:38:23.185274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f51515ef13a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_table('eqptmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eqptmodel_name'), 'eqptmodel', ['name'], unique=False)
    op.create_table('log_client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('event', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_client_client_id'), 'log_client', ['client_id'], unique=False)
    op.create_index(op.f('ix_log_client_initiator_id'), 'log_client', ['initiator_id'], unique=False)
    op.create_table('nas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nasname', sa.String(length=128), nullable=False),
    sa.Column('shortname', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('ports', sa.Integer(), nullable=True),
    sa.Column('secret', sa.String(length=60), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=True),
    sa.Column('community', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nas_nasname'), 'nas', ['nasname'], unique=False)
    op.create_table('network',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('svlan', sa.Integer(), nullable=False),
    sa.Column('netlan', sa.BigInteger(), nullable=False),
    sa.Column('netmask', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.BigInteger(), nullable=True),
    sa.Column('dns', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netlan')
    )
    op.create_table('radacct',
    sa.Column('radacctid', sa.BigInteger(), nullable=False),
    sa.Column('acctsessionid', sa.String(length=64), nullable=False),
    sa.Column('acctuniqueid', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('realm', sa.String(length=64), nullable=True),
    sa.Column('nasipaddress', sa.String(length=15), nullable=False),
    sa.Column('nasportid', sa.String(length=15), nullable=True),
    sa.Column('nasporttype', sa.String(length=32), nullable=True),
    sa.Column('acctstarttime', sa.DateTime(), nullable=True),
    sa.Column('acctupdatetime', sa.DateTime(), nullable=True),
    sa.Column('acctstoptime', sa.DateTime(), nullable=True),
    sa.Column('acctinterval', sa.BigInteger(), nullable=True),
    sa.Column('acctsessiontime', sa.BigInteger(), nullable=True),
    sa.Column('acctauthentic', sa.String(length=32), nullable=True),
    sa.Column('connectinfo_start', sa.String(length=50), nullable=True),
    sa.Column('connectinfo_stop', sa.String(length=50), nullable=True),
    sa.Column('acctinputoctets', sa.BigInteger(), nullable=True),
    sa.Column('acctoutputoctets', sa.BigInteger(), nullable=True),
    sa.Column('calledstationid', sa.String(length=50), nullable=False),
    sa.Column('callingstationid', sa.String(length=50), nullable=False),
    sa.Column('acctterminatecause', sa.String(length=32), nullable=False),
    sa.Column('servicetype', sa.String(length=32), nullable=True),
    sa.Column('framedprotocol', sa.String(length=32), nullable=True),
    sa.Column('framedipaddress', sa.String(length=15), nullable=False),
    sa.Column('framedipv6address', sa.String(length=45), nullable=False),
    sa.Column('framedipv6prefix', sa.String(length=45), nullable=False),
    sa.Column('framedinterfaceid', sa.String(length=44), nullable=False),
    sa.Column('delegatedipv6prefix', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('radacctid'),
    sa.UniqueConstraint('acctuniqueid')
    )
    op.create_index(op.f('ix_radacct_acctinterval'), 'radacct', ['acctinterval'], unique=False)
    op.create_index(op.f('ix_radacct_acctsessionid'), 'radacct', ['acctsessionid'], unique=False)
    op.create_index(op.f('ix_radacct_acctsessiontime'), 'radacct', ['acctsessiontime'], unique=False)
    op.create_index(op.f('ix_radacct_acctstarttime'), 'radacct', ['acctstarttime'], unique=False)
    op.create_index(op.f('ix_radacct_acctstoptime'), 'radacct', ['acctstoptime'], unique=False)
    op.create_index(op.f('ix_radacct_delegatedipv6prefix'), 'radacct', ['delegatedipv6prefix'], unique=False)
    op.create_index(op.f('ix_radacct_framedinterfaceid'), 'radacct', ['framedinterfaceid'], unique=False)
    op.create_index(op.f('ix_radacct_framedipaddress'), 'radacct', ['framedipaddress'], unique=False)
    op.create_index(op.f('ix_radacct_framedipv6address'), 'radacct', ['framedipv6address'], unique=False)
    op.create_index(op.f('ix_radacct_framedipv6prefix'), 'radacct', ['framedipv6prefix'], unique=False)
    op.create_index(op.f('ix_radacct_nasipaddress'), 'radacct', ['nasipaddress'], unique=False)
    op.create_index(op.f('ix_radacct_username'), 'radacct', ['username'], unique=False)
    op.create_table('radcheck',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radcheck_username'), 'radcheck', ['username'], unique=True)
    op.create_table('radgroupcheck',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radgroupcheck_groupname'), 'radgroupcheck', ['groupname'], unique=False)
    op.create_table('radgroupreply',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radgroupreply_groupname'), 'radgroupreply', ['groupname'], unique=False)
    op.create_table('radpostauth',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pass', sa.String(length=64), nullable=False),
    sa.Column('reply', sa.String(length=32), nullable=False),
    sa.Column('authdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radpostauth_username'), 'radpostauth', ['username'], unique=False)
    op.create_table('radreply',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radreply_username'), 'radreply', ['username'], unique=True)
    op.create_table('radusergroup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radusergroup_username'), 'radusergroup', ['username'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('eqpt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.BigInteger(), nullable=False),
    sa.Column('serial', sa.String(length=50), nullable=False),
    sa.Column('mac', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('cvlan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['eqptmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eqpt_building_id'), 'eqpt', ['building_id'], unique=False)
    op.create_index(op.f('ix_eqpt_ip'), 'eqpt', ['ip'], unique=False)
    op.create_index(op.f('ix_eqpt_mac'), 'eqpt', ['mac'], unique=False)
    op.create_index(op.f('ix_eqpt_network_id'), 'eqpt', ['network_id'], unique=False)
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_street_name'), 'street', ['name'], unique=False)
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_name'), 'building', ['name'], unique=False)
    op.create_table('eqptport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eqpt_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('cvlan', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('radius_user', sa.String(length=20), nullable=False),
    sa.Column('radius_pass', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['eqpt_id'], ['eqpt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eqptport_cvlan'), 'eqptport', ['cvlan'], unique=False)
    op.create_index(op.f('ix_eqptport_radius_user'), 'eqptport', ['radius_user'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('eqptport_id', sa.Integer(), nullable=True),
    sa.Column('fio', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('apartment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspension_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['eqptport_id'], ['eqptport.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_building_id'), 'client', ['building_id'], unique=False)
    op.create_index(op.f('ix_client_fio'), 'client', ['fio'], unique=False)
    op.create_index(op.f('ix_client_phone'), 'client', ['phone'], unique=False)
    op.create_index(op.f('ix_client_status'), 'client', ['status'], unique=False)
    op.create_index(op.f('ix_client_suspension_at'), 'client', ['suspension_at'], unique=False)
    op.create_table('networkhost',
    sa.Column('host', sa.BigInteger(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('eqptport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eqptport_id'], ['eqptport.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('host')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('networkhost')
    op.drop_index(op.f('ix_client_suspension_at'), table_name='client')
    op.drop_index(op.f('ix_client_status'), table_name='client')
    op.drop_index(op.f('ix_client_phone'), table_name='client')
    op.drop_index(op.f('ix_client_fio'), table_name='client')
    op.drop_index(op.f('ix_client_building_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_eqptport_radius_user'), table_name='eqptport')
    op.drop_index(op.f('ix_eqptport_cvlan'), table_name='eqptport')
    op.drop_table('eqptport')
    op.drop_index(op.f('ix_building_name'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_street_name'), table_name='street')
    op.drop_table('street')
    op.drop_index(op.f('ix_eqpt_network_id'), table_name='eqpt')
    op.drop_index(op.f('ix_eqpt_mac'), table_name='eqpt')
    op.drop_index(op.f('ix_eqpt_ip'), table_name='eqpt')
    op.drop_index(op.f('ix_eqpt_building_id'), table_name='eqpt')
    op.drop_table('eqpt')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_radusergroup_username'), table_name='radusergroup')
    op.drop_table('radusergroup')
    op.drop_index(op.f('ix_radreply_username'), table_name='radreply')
    op.drop_table('radreply')
    op.drop_index(op.f('ix_radpostauth_username'), table_name='radpostauth')
    op.drop_table('radpostauth')
    op.drop_index(op.f('ix_radgroupreply_groupname'), table_name='radgroupreply')
    op.drop_table('radgroupreply')
    op.drop_index(op.f('ix_radgroupcheck_groupname'), table_name='radgroupcheck')
    op.drop_table('radgroupcheck')
    op.drop_index(op.f('ix_radcheck_username'), table_name='radcheck')
    op.drop_table('radcheck')
    op.drop_index(op.f('ix_radacct_username'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_nasipaddress'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_framedipv6prefix'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_framedipv6address'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_framedipaddress'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_framedinterfaceid'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_delegatedipv6prefix'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_acctstoptime'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_acctstarttime'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_acctsessiontime'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_acctsessionid'), table_name='radacct')
    op.drop_index(op.f('ix_radacct_acctinterval'), table_name='radacct')
    op.drop_table('radacct')
    op.drop_table('network')
    op.drop_index(op.f('ix_nas_nasname'), table_name='nas')
    op.drop_table('nas')
    op.drop_index(op.f('ix_log_client_initiator_id'), table_name='log_client')
    op.drop_index(op.f('ix_log_client_client_id'), table_name='log_client')
    op.drop_table('log_client')
    op.drop_index(op.f('ix_eqptmodel_name'), table_name='eqptmodel')
    op.drop_table('eqptmodel')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
