"""add svaln to eqpt

Revision ID: e4bead470924
Revises: 4606822aa4f4
Create Date: 2019-10-21 12:04:24.214534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bead470924'
down_revision = '4606822aa4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eqpt', sa.Column('cvlan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eqpt', 'cvlan')
    # ### end Alembic commands ###
